### ISSUE TITLE
Nginx

### ISSUE THREAD

**Issue by balya** [waifung0207/ci_bootstrap#7] opened 2015-06-09 20:16 UTC
Please, help to create Nginx Config for rewrite rules.

**Comment by waifung0207** [comment] 2015-06-19 04:33
I am not really good at Nginx configuration, but I also tried to do the same thing however couldn't really get it works... :(

The closest config I used is like this: (not tested for latest repo)
https://gist.github.com/waifung0207/837482a6f85096445230

But the issue is, even I can rewrite the URL like from http://ci_bootstrap/index.php/login to http://ci_bootstrap/login, seems the config cannot work with Backend URL, e.g. http://ci_bootstrap/backend.php/login (which will should server error as I remember - only tried quite a long time ago)

I would appreciate if you can figure out a solution on this, sorry that I cannot help much here.

By the way, I am working on another repository named ci_bootstrap_3 which make use of CodeIgniter v3 with HMVC structure, from there it should work properly with the Nginx config even for Backend System. If you are interested feel free to visit: https://github.com/waifung0207/ci_bootstrap_3

Even I am mentioning work in progress in that repo, the folder structure should be fixed and I am just focusing on the stability and writing doc about it. 

Thanks.

**Closed as completed** 2015-07-27 10:57 UTC
